[package]
name = "agb"
version = "0.6.0"
authors = ["Corwin Kuiper <corwin@kuiper.dev>", "Gwilym Kuiper <gw@ilym.me>"]
edition = "2018"
description = "Library for Game Boy Advance Development"
license = "MPL-2.0"

[profile.dev]
opt-level = 3
debug = true
lto = "thin"

[profile.release]
lto = true
debug = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2"
agb_image_converter = { version = "0.6.0", path = "../agb-image-converter" }

[package.metadata.docs.rs]
default-target = "thumbv6m-none-eabi"
targets = []
